export const ADD_LAYOUT_OPTION = 'ADD_LAYOUT_OPTION';
export const REMOVE_LAYOUT_OPTION = 'REMOVE_LAYOUT_OPTION';
export const SWAP_LAYOUT_OPTIONS = 'SWAP_LAYOUT_OPTIONS';
export const SELECT_LAYOUT_OPTION = 'SELECT_LAYOUT_OPTION';
export const UPDATE_SELECTED_LAYOUT_OPTION = 'UPDATE_SELECTED_LAYOUT_OPTION';